In [12]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [18]:
BASE = "/content/drive/MyDrive/MultiModalProject/Flickr8k"

In [19]:
import pandas as pd
import numpy as np
import os

In [20]:
os.listdir(BASE)

['captions.txt', 'Images']

In [21]:
import pandas as pd

df = pd.read_csv(
    f"{BASE}/captions.txt"
)

df.head()

,image,caption
0,1000268201_693b08cb0e.jpg,A child in a pink dress is climbing up a set o...
1,1000268201_693b08cb0e.jpg,A girl going into a wooden building .
2,1000268201_693b08cb0e.jpg,A little girl climbing into a wooden playhouse .
3,1000268201_693b08cb0e.jpg,A little girl climbing the stairs to her playh...
4,1000268201_693b08cb0e.jpg,A little girl in a pink dress going into a woo...

In [22]:
print(df.head())

print(df.shape)

print(df.isnull().sum())

print(df.describe())

                       image  \
0  1000268201_693b08cb0e.jpg
1  1000268201_693b08cb0e.jpg
2  1000268201_693b08cb0e.jpg
3  1000268201_693b08cb0e.jpg
4  1000268201_693b08cb0e.jpg

                                             caption
0  A child in a pink dress is climbing up a set o...
1              A girl going into a wooden building .
2   A little girl climbing into a wooden playhouse .
3  A little girl climbing the stairs to her playh...
4  A little girl in a pink dress going into a woo...
(40455, 2)
image      0
caption    0
dtype: int64
                           image                         caption
count                      40455                           40455
unique                      8091                           40201
top     997722733_0cb5439472.jpg  Two dogs playing in the snow .
freq                           5                               7

In [23]:
print("Before:", len(df))

df = df.drop_duplicates()

print("After:", len(df))

Before: 40455
After: 40445

In [24]:
import re

def clean_caption(text):
    text = text.lower()

    text = re.sub(r"[^a-zA-Z ]", "", text)

    text = re.sub(r"\s+", " ", text)

    return text.strip()

df["caption"] = df["caption"].apply(clean_caption)

In [25]:
df.head()

,image,caption
0,1000268201_693b08cb0e.jpg,a child in a pink dress is climbing up a set o...
1,1000268201_693b08cb0e.jpg,a girl going into a wooden building
2,1000268201_693b08cb0e.jpg,a little girl climbing into a wooden playhouse
3,1000268201_693b08cb0e.jpg,a little girl climbing the stairs to her playh...
4,1000268201_693b08cb0e.jpg,a little girl in a pink dress going into a woo...

In [26]:
df["caption"] = df["caption"].apply(
    lambda x: "<start> " + x + " <end>"
)

In [27]:
from sklearn.model_selection import train_test_split

images = df["image"].unique()

train_imgs, test_imgs = train_test_split(
    images,
    test_size=0.2,
    random_state=42
)

train_imgs, val_imgs = train_test_split(
    train_imgs,
    test_size=0.1,
    random_state=42
)

In [28]:
train_df = df[df.image.isin(train_imgs)]

val_df = df[df.image.isin(val_imgs)]

test_df = df[df.image.isin(test_imgs)]

In [29]:
print(train_df.shape)
print(val_df.shape)
print(test_df.shape)

(29112, 2)
(3238, 2)
(8095, 2)

In [30]:
print("Train Images:", train_df["image"].nunique())
print("Validation Images:", val_df["image"].nunique())
print("Test Images:", test_df["image"].nunique())

Train Images: 5824
Validation Images: 648
Test Images: 1619

In [31]:
print(set(train_df["image"]).intersection(set(val_df["image"])))
print(set(train_df["image"]).intersection(set(test_df["image"])))
print(set(val_df["image"]).intersection(set(test_df["image"])))

set()
set()
set()

In [32]:
train_df.to_csv(f"{BASE}/dataset_caption_train.csv", index=False)
val_df.to_csv(f"{BASE}/dataset_caption_val.csv", index=False)
test_df.to_csv(f"{BASE}/dataset_caption_test.csv", index=False)